name: real_estate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  json_serializable: 3.5.1
  json_annotation: 3.1.1
  shared_preferences: ^2.0.5
  curved_navigation_bar: ^0.3.7
  cached_network_image: '2.5.1'
  flutter_money_formatter: ^0.8.3
  carousel_slider: ^3.0.0
  flutter_range_slider: ^1.5.0
  multi_image_picker: ^4.8.0
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  flutter_google_places: '0.2.8'
  flutter_easyloading: ^3.0.0
  http_parser: ^4.0.0
  http: ^0.13.1
  flutter_absolute_path: ^1.0.6
  location: ^4.1.1
  


dependency_overrides:
  intl: any
  
dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4

flutter_native_splash:
  color: "#ffffff"
  image: images/real.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/profilePage.png
    - images/login.png
    - images/register.png
    - images/male.png
    - images/fmale.png
    - images/real.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
